version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crud-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-ecxfam9yniqc"
s3_prefix = "crud-app"
region = "us-west-2"
capabilities = "CAPABILITY_IAM"
disable_rollback = true
image_repositories = []
confirm_changeset = true
